coverage:
  precision: 2
  round: down
  range: 70..100

  status:
    project:
      default:
        target: 90%
        threshold: 2%
    patch:
      default:
        target: 90%

comment:
  layout: "reach,diff,tree"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true

ignore:
  - "tests/*"
